### ISSUE TITLE
Implement `SemiEvalDataIO._load_data`

### ISSUE THREAD

**Issue by dinever** [toothacher17/deep-relation#4]
`SemiEvalDataIO._load_data` should load a training/testing file like https://github.com/toothacher17/deep-relation/blob/master/dataprep/src/main/resources/semieval-2018-task8/train/TRAIN_FILE.TXT

It should create a `SemiEvalData` object for each record of the file.

/cc @toothacher17

**Comment by toothacher17** [comment]
Yes, thanks for creating the issue
